### ISSUE TITLE
最后一步出现问题了

### ISSUE THREAD

**Issue by xizhedong** [hamflx/huawei-pc-manager-bootstrap#1]
![image](https://user-images.githubusercontent.com/69316039/159665401-277d61a8-845d-46ef-a9e0-8a59a1032f97.png)

**Comment by xizhedong** [comment]
![image](https://user-images.githubusercontent.com/69316039/159665707-ba46b92c-2e86-4f1b-965f-533eb90db6a2.png)
我把huawei电脑安装软件放在同一目录

**Comment by hamflx** [comment]
未能复现该问题，请把 `PCManager_Setup_12.0.1.26(C233D003).exe` 替换成绝对路径试试，确保用 cmd 输入这个绝对路径能打开。

**Comment by xizhedong** [comment]
thank you,我用其他解决安装问题


> 未能复现该问题，请把 `PCManager_Setup_12.0.1.26(C233D003).exe` 替换成绝对路径试试，确保用 cmd 输入这个绝对路径能打开。

**Comment by xizhedong** [comment]
> 未能复现该问题，请把 `PCManager_Setup_12.0.1.26(C233D003).exe` 替换成绝对路径试试，确保用 cmd 输入这个绝对路径能打开。

今天没事的时候运行一下，运行成功了。之前用cmd编译的，可能没编译好。今天换成powershell成功了
![image](https://user-images.githubusercontent.com/69316039/160227042-b270f4b8-f17c-4b98-bbdb-f9cb2a016606.png)

**Comment by hamflx** [comment]
目前还是隔壁的汉客儿的方案有效，主要是安装后的功能我还没有实现，但是他的方案是闭源的。
