### ISSUE TITLE
闪退, 没有 log

### ISSUE THREAD

**Issue by jiucenglou** [hamflx/huawei-pc-manager-bootstrap#10]
目录为字母, 但是运行时闪退, 在 `AppData\Local\hamflx\huawei_pc_manager_bootstrap\cache` 下没有 log 文件, 没有头绪, 请您帮忙看看, 谢谢 !

**Comment by hamflx** [comment]
是华为电脑管家闪退，还是安装器闪退？操作系统是？显卡是（安装器 UI 用的 egui，需要用显卡渲染）？显卡驱动更新下看看？有没有在虚拟机内执行？

**Comment by jiucenglou** [comment]
谢谢帮助 ! 安装器闪退, 根据您的提示, 原因应该是 rdp 远程桌面, 到屏幕前可以安装了 :D
