### ISSUE TITLE
感谢大佬分享昨天编译的时候提示错误https://github.com/hamflx/sysinfo.git不存在请问怎么解决？

### ISSUE THREAD

**Issue by cainiaoshangxian** [hamflx/huawei-pc-manager-bootstrap#16]
大佬看见了告诉我替代办法或者解决办法哈，非常感谢~

**Comment by hamflx** [comment]
拉最新代码。

**Comment by cainiaoshangxian** [comment]
> 拉最新代码。

好的，我今天试试看~

**Comment by cainiaoshangxian** [comment]
> 拉最新代码。
warning: spurious network error (2 tries remaining): request failed with status code: 404; class=Http (34)

**Comment by cainiaoshangxian** [comment]
> 拉最新代码。

提示这个错误需要挂梯子吗

**Comment by hamflx** [comment]
你原先代码是怎么拉下来的，这个得看情况，看地区，你可以用梯子试试，能保证拉成功。

**Comment by cainiaoshangxian** [comment]
> 你原先代码是怎么拉下来的，这个得看情况，看地区，你可以用梯子试试，能保证拉成功。

原先就是用桌面端和你的方法都试了，能下载编译的时候会卡错误

我现在挂了梯子，提示我

warning: spurious network error (2 tries remaining): failed to send request: 操作超时
; class=Os (2)

**Comment by hamflx** [comment]
确实有问题，之前整理依赖的时候把仓库删掉了，有一部分没改过来，我修改下依赖路径。

**Comment by cainiaoshangxian** [comment]
> 确实有问题，之前整理依赖的时候把仓库删掉了，有一部分没改过来，我修改下依赖路径。

好的，大佬搞好的和我说一下，我这边在试试看~

**Comment by hamflx** [comment]
再试下。
