### ISSUE TITLE
华为分享

### ISSUE THREAD

**Issue by xizhedong** [hamflx/huawei-pc-manager-bootstrap#2]
### **我的电脑华为分享用不了，但是多屏协同能用。该如何配置才能使华为分享能用。**
![image](https://user-images.githubusercontent.com/69316039/160227357-75e42e3f-09b6-4903-94e2-03454d212283.png)
### **这是我的硬件信息**
![image](https://user-images.githubusercontent.com/69316039/160227431-e1297e44-8698-456b-85af-05430313c1d6.png)
### **恳求大佬指点**

**Comment by hamflx** [comment]
你是用这个仓库的方案安装的吗？目前这个方式安装的华为电脑管家有部分功能无法使用（华为分享我目前还没有测试，不知道是不是这个原因），因为只是绕过了安装检查，安装之后华为电脑管家内部还是有其它限制。如果要用的话可以尝试隔壁汉克尔的 `version.dll`（这个是注入到华为电脑管家的程序，可以绕过运行时的限制，但是未开源）。

**Comment by xizhedong** [comment]
最开始用的汉克尔的 `version.dll`，不行的。但我室友非华为电脑可以用华为分享，我觉可能是我的电脑太老了。软件无法适配该电脑，我想有没有方法做一些软件修改让他能够运行

**Comment by hamflx** [comment]
那你可以试试更新下驱动看看，如果还不行那就不好弄了。

**Comment by xizhedong** [comment]
已在官网更新了驱动，不管用，(●'◡'●)

**Comment by hamflx** [comment]
我发现 `HardwareHal.dll` 里面有个函数 `SmBiosHelper::IsUnsupportWifiAndBT`，可以试试改改返回值看能不能生效。

![image](https://user-images.githubusercontent.com/13356747/162490332-09f95bc6-8c52-46f3-a8a1-3f8ff115bbdf.png)

**Comment by xizhedong** [comment]
我不知道该修改那个dll
![image](https://user-images.githubusercontent.com/69316039/162612435-9846d867-6c5e-44c3-b5ff-3ef3138db941.png)
我是个小白，不知道怎么弄。不知道如何打开dll。也不知道怎么改返回值
恳请大佬细心指导(●'◡'●)

**Comment by hamflx** [comment]
我试验了一下，跟这个方法没有关系，如果这个方法返回了 true 的话连整个华为分享模块都不会显示出来。

**Comment by xizhedong** [comment]
好吧,还是很感谢你👍

**Comment by AelepantB** [comment]
+1，我也遇到这个问题。多屏协同正常使用，华为分享可以在华为控制中心正常开启但是手机无法连接。只有在多屏协同时，剪切板才能跨设备。停止多屏协同就不在剪切板跨设备。

![image](https://github.com/hamflx/huawei-pc-manager-bootstrap/assets/104605918/b5fb2b8a-bac6-4ee2-8aff-5f0b1f4054d5)
