### ISSUE TITLE
手机多屏协同功能正常，平板能连接但是不能用

### ISSUE THREAD

**Issue by mashumashu2333** [hamflx/huawei-pc-manager-bootstrap#20]
已下载并成功安装

电脑管家版本：13.0.6.330(C233)
已检查设备设备管理器，Virtual HID Device、Indirect Display Bus System Device、Virtual Display Device均已安装，可以使用无线直接搜索并连接手机和平板

1、手机Mate 50 RS 正常链接，并可以从手机端或者PC端发起多屏协同
2、平板MatePad Pro 12.6，HarmonyOS版本3.0.0,，可以连接但多屏协同异常
异常部分：
（1）镜像、扩展功能点击后，电脑出现投影开启视觉效果，显示器也能检测到Virtual Display Device，但是平板端一直显示协同连接中。10多秒后电脑和平板同时退出协同，Virtual Display Device自动关闭。偶然有一次扩展连上了，但是平板端一直黑屏不显示内容，鼠标可以正常移动到平板（能看到移动到边界的穿越动画）
正常部分：
（2）共享功能可以使用，鼠标、键盘均能正常在PC和平板上操作。有个小毛病是每次开启共享功能，数字键盘会自动关闭
（3）查看平板文件、跨款设备拖拽文件（共享开启时）等均可以使用

非常感谢您的分享，电脑管家的多屏协同是安装成功的。本人非相关行业也没有学习过这些，无法判断是官方自身的协同问题还是其他原因导致的。
PS：前几年安装过电脑管家，好像是10的大版本（记不太清），当时是OS2.0可以使用的，后续更新到OS3.0每次协同出来就黑屏了，直至去年9月系统重装没再用过电脑管家。

**Comment by hamflx** [comment]
没有平板，有估计也搞不定，可能是驱动兼容性问题。

**Comment by mashumashu2333** [comment]
好的，谢谢
