### ISSUE TITLE
无法写入补丁

### ISSUE THREAD

**Issue by filusilia** [hamflx/huawei-pc-manager-bootstrap#4]
v0.13
联想l490
安装完就提示被占用，然后无法写入补丁，软件也无法正常打开，会直接闪退。

**Comment by hamflx** [comment]
点击“安装”按钮会自动写入补丁的。可以把日志贴出来看一下。另外可以试试把华为电脑管家目录中的version.dll删除了，看看会不会闪退。

**Comment by hamflx** [comment]
还有就是你安装的是哪个版本的华为电脑管家。

**Comment by hamflx** [comment]
另外，安装过程中是否把安装器关了？

**Comment by hamflx** [comment]
确保 vcruntime140 已经安装。

**Comment by filusilia** [comment]
140已经装了，安装的版本是官网的26，现在尝试卸载重装感觉也不太行，可能卸载不干净还是会闪退。
删除version的话，会提示要修复，修复完了就还是闪退。。

**Comment by hamflx** [comment]
卸载后要重新启动系统才可以再次安装，不然就会有卸载不干净问题。

**Comment by hamflx** [comment]
重启然后重新安装，并删除 version.dll 也崩溃是吧？崩溃是没有任何提示吗？你把无线网、蓝牙禁了看看？

**Comment by hamflx** [comment]
没有关闭蓝牙和 WIFI 是吗？就重新安装一下然后删除 version.dll 就不闪退了是吧？那你再试试从回收站恢复 version.dll 试试看会不会闪退。

**Comment by hamflx** [comment]
如果要删除 version.dll 提示你无法删除的话，需要在任务管理器里终止以下进程：MBA... 进程、Hw... 进程、LCD 进程、PCMana... 进程、MateBook...。

**Comment by hamflx** [comment]
应该没有蓝牙协同这个说法吧，你指的是多屏协同吧？这个需要 version.dll 的支持，也就是这个仓库所提供的补丁。

**Comment by filusilia** [comment]
恢复补丁会报错 dfssearchservice.exe错误，无法正常启动， 报错信息0xc0000142

**Comment by filusilia** [comment]
打开软件打开2s就会报这个错误退出软件

**Comment by hamflx** [comment]
那可能是触发了一个 bug，等我有时间看一下。可以把日志提供一下吗？

**Comment by hamflx** [comment]
你可以看下 README.md 中其他开发者的方案，或者帮我修复掉这个 bug :)

**Comment by hamflx** [comment]
没能完全复现，找到一个可能崩溃的原因，发布了 v0.1.4 版本，你可以试下。另外加了个“终止所有进程”的功能，如果 `version.dll` 被占用了无法覆盖或删除，点这个按钮就可以杀掉所有的华为进程。

**Comment by filusilia** [comment]
更新了0.14安装，还是一样的。安装完无法启动，但是删除掉version可以启动了。

**Comment by filusilia** [comment]
额...最新消息,我尝试了空降猫咪发的最新的安装程序下的version,可以正常使用了...

**Comment by hamflx** [comment]
问题已修复，v0.1.5 已发布。
