### ISSUE TITLE
大佬您好，想问一下最新版电脑管家又加了什么限制

### ISSUE THREAD

**Issue by w19996** [hamflx/huawei-pc-manager-bootstrap#6]
我修改了BIOS信息，把机型，主板型号修改成了华为的，老版本可以安装，最新版不能安装了，提示暂不支持此版本的安装，不知道又加了什么限制，大佬可以告诉我吗

**Comment by hamflx** [comment]
你怎么修改的 BIOS 信息啊？另外，最新版本又是哪个版本啊？

**Comment by w19996** [comment]
> 你怎么修改的 BIOS 信息啊？另外，最新版本又是哪个版本啊？

https://www.coolapk.com/feed/30338113?shareKey=MGZhZTJlNmQwMzUxNjJjMjZiZTk~&shareUid=3105856&shareFrom=com.coolapk.market_12.1.1
不过我的BIOS是insyde的，用insyde对应的软件可以修改，修改完鲁大师检测也是华为的机型

版本是12.0.1.26

**Comment by hamflx** [comment]
修改 BIOS 的方案我也没有尝试过，不知道为什么不行，你可以找那篇文章的博主咨询。

**Comment by w19996** [comment]
> 修改 BIOS 的方案我也没有尝试过，不知道为什么不行，你可以找那篇文章的博主咨询。

谢谢，问过博主了，他没有折腾新版的了

您这个程序也是伪装的华为的机型吧，所以我想问一下都伪装了哪些信息

**Comment by hamflx** [comment]
安装阶段没有任何伪装，因为安装阶段是 NSIS 安装脚本运行一个程序 `MBAInstallPre isSupportDevice` 检测是否可以安装，我直接让这个进程终止了，然后设置这个进程的退出状态。

有一篇文章讲解了 `MBAInstallPre isSupportDevice` 的劫持过程：<https://bbs.pediy.com/thread-270682.htm>，他是做了以下的参数修改：`Manufacturer`、`ProductName`、`Version`、`SN`。

该仓库运行阶段是改了：`Manufacturer`、`ProductName`、`Version`、`SN`、`SKUNumber`。

**Comment by w19996** [comment]
> 安装阶段没有任何伪装，因为安装阶段是 NSIS 安装脚本运行一个程序 `MBAInstallPre isSupportDevice` 检测是否可以安装，我直接让这个进程终止了，然后设置这个进程的退出状态。
> 
> 有一篇文章讲解了 `MBAInstallPre isSupportDevice` 的劫持过程：<https://bbs.pediy.com/thread-270682.htm>，他是做了以下的参数修改：`Manufacturer`、`ProductName`、`Version`、`SN`。
> 
> 该仓库运行阶段是改了：`Manufacturer`、`ProductName`、`Version`、`SN`、`SKUNumber`。
> 

好的，谢谢大佬
