### ISSUE TITLE
如何通过配置文件修改sn

### ISSUE THREAD

**Issue by gepcel** [hamflx/huawei-pc-manager-bootstrap#8]
我看到最近的一次更新提到“支持用配置文件设置厂商/产品名称/SN/Sku”，能否略做讲解或示例如何使用配置文件？

**Comment by hamflx** [comment]
主界面有个打开配置按钮，会用 notepad 打开，是一个 json 格式的文件，你可以根据情况修改。

**Comment by hamflx** [comment]
编辑之后，需要重启电脑管家才会生效。

**Comment by hamflx** [comment]
![image](https://user-images.githubusercontent.com/13356747/183654682-7c468889-49dc-43c5-a565-3bad550375ad.png)

**Comment by filusilia** [comment]
不知道支持13了没  不太敢试

**Comment by hamflx** [comment]
@filusilia 我已经试了，没啥大问题，多屏协同貌似还更稳定了，以前经常断。

但是呢，我这个工具并没有修改电脑管家的配置文件，13 支持的一些新东西这里并没有显示出来，得自己改电脑管家的配置文件。可以去 b 站找其他大佬的软件（或配置方法）玩那些功能 :D。

**Comment by gepcel** [comment]
> 主界面有个打开配置按钮，会用 notepad 打开，是一个 json 格式的文件，你可以根据情况修改。

我刚下载了出现的 0.1.9 的版本， 打开配置之后，出现的 config.json 是个空白文件，完全没有内容的。是需要在安装完管家之后再操作这一步骤吗？我是在安装之前打开的。

**Comment by hamflx** [comment]
@gepcel 如果你是已经安装过的了，需要“终止所有程序”→“安装补丁”→“打开配置”。因为配置文件默认是没有的，只有安装补丁时才会默认写入一个初始配置。

**Comment by gepcel** [comment]
换台电脑试，找到了。大致步骤是：
安装-终止所有程序-安装补丁-打开管家查看SN-打开配置（这一次找到了config.json）-修改sn-保存-重启
